name: Release

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        description: 'The environment to release to.'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy
        run: Echo "deploying to ${{ inputs.environment }}"
