name: Release

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        description: 'The environment to release to.'

jobs:
  prepare:
    environment: production
    runs-on: ubuntu-latest
    name: Prepare
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare
        run: echo "preparing for ${{ inputs.environment }}"
  build:
    environment: production
    runs-on: ubuntu-latest
    name: Build
    needs:
      - prepare
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: echo "building for ${{ inputs.environment }}"
  deploy:
    environment: production
    runs-on: ubuntu-latest
    name: Deploy
    needs:
      - build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy
        run: echo "deploying to ${{ inputs.environment }}"
