name: Release production

on:
  push:
    tags:
      - release/production/*

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
  deploy:
    name: Deploy / Production
    uses: ./.github/workflows/release.yml
    with:
      environment: production
