name: Release production

on:
  push:
    tags:
      - release/production/*

jobs:
  release-shared:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: ./.github/workflows/release.yml
        with:
          environment: production
